import { Dirent } from "node:fs"
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises"
import path, { dirname, extname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"
import svgSpritemap from "@spiriit/vite-plugin-svg-spritemap"
import chokidar, { type FSWatcher } from "chokidar"
import type { Plugin, ViteDevServer } from "vite"

const projectRoot = fileURLToPath(new URL("..", import.meta.url))
const iconRoot = join(projectRoot, "src/icons")
const outputPath = join(projectRoot, "src/support/svg-icon-data.ts")
const templatePath = fileURLToPath(new URL("./svg-icon-data.template.ts", import.meta.url))
const generatedBanner =
  "// Generated by the Vite svg icon build plugin. Edit the template instead.\n\n"

/** Generates the SvgIcon data module from SVG assets under `src/icons`. */
export default function svgIconBuildPlugin(): Plugin[] {
  let fileWatcher: FSWatcher | null = null
  let regenerateQueue = Promise.resolve()

  return [
    {
      name: "goddard-ai:svg-icon-build-plugin",
      async buildStart() {
        await generateSvgIconDataModule()
      },
      configureServer(server: ViteDevServer) {
        const queueRegeneration = (filePath: string) => {
          if (filePath !== templatePath && !isIconPath(filePath)) {
            return
          }

          regenerateQueue = regenerateQueue.then(async () => {
            await generateSvgIconDataModule()

            const module = server.moduleGraph.getModuleById(outputPath)
            if (module) {
              server.moduleGraph.invalidateModule(module)
            }

            server.ws.send({ type: "full-reload" })
          })
        }

        fileWatcher?.close()
        fileWatcher = chokidar.watch([iconRoot, templatePath], {
          ignoreInitial: true,
          awaitWriteFinish: {
            stabilityThreshold: 50,
            pollInterval: 10,
          },
        })

        fileWatcher.on("add", queueRegeneration)
        fileWatcher.on("change", queueRegeneration)
        fileWatcher.on("unlink", queueRegeneration)

        server.httpServer?.once("close", () => {
          fileWatcher?.close()
          fileWatcher = null
        })
      },
      async closeBundle() {
        await fileWatcher?.close()
        fileWatcher = null
      },
    },
    ...svgSpritemap("../icons/**/*.svg", {
      idify: (_name, svg) => getSvgIconSymbolId(getSvgIconNameFromFilePath(svg.filePath)),
      prefix: false,
    }),
  ]
}

/** Rebuilds the generated SvgIcon data module from the current SVG asset set. */
export async function generateSvgIconDataModule() {
  console.log("Generating SVG icon data...")
  await mkdir(iconRoot, { recursive: true })

  const template = await readFile(templatePath, "utf8")
  const iconEntries = await getSvgIconEntries()
  const generatedSource = template.replace(
    "/* SVG_ICON_ENTRIES */",
    buildIconEntryBlock(iconEntries),
  )
  const generated = injectGeneratedBanner(generatedSource)

  await mkdir(dirname(outputPath), { recursive: true })

  let existing = ""

  try {
    existing = await readFile(outputPath, "utf8")
  } catch {
    existing = ""
  }

  if (existing === generated) {
    return
  }

  await writeFile(outputPath, generated)
}

/** Returns the app-level icon name derived from one SVG file path. */
function getSvgIconNameFromFilePath(filePath: string) {
  const relativeIconPath = relative(iconRoot, filePath)
  return toPosixPath(relativeIconPath.slice(0, -extname(relativeIconPath).length))
}

/** Returns the spritemap symbol id for one app-level icon name. */
function getSvgIconSymbolId(name: string) {
  return name
    .replaceAll(/[^a-zA-Z0-9]+/g, "-")
    .replaceAll(/^-+|-+$/g, "")
    .toLowerCase()
}

async function getSvgIconEntries() {
  const iconPaths = await listSvgFilePaths(iconRoot)

  return iconPaths
    .sort((left, right) => left.localeCompare(right))
    .map((filePath) => {
      const iconName = getSvgIconNameFromFilePath(filePath)

      return {
        iconName,
        symbolId: getSvgIconSymbolId(iconName),
      }
    })
}

async function listSvgFilePaths(directoryPath: string) {
  let directoryEntries: Dirent[]

  try {
    directoryEntries = await readdir(directoryPath, {
      recursive: true,
      withFileTypes: true,
    })
  } catch {
    return []
  }

  const svgPaths: string[] = []

  for (const directoryEntry of directoryEntries) {
    if (!directoryEntry.isFile() || extname(directoryEntry.name).toLowerCase() !== ".svg") {
      continue
    }

    const parentPath = "parentPath" in directoryEntry ? directoryEntry.parentPath : directoryPath
    svgPaths.push(join(parentPath, directoryEntry.name))
  }

  return svgPaths
}

function buildIconEntryBlock(iconEntries: Array<{ iconName: string; symbolId: string }>) {
  if (iconEntries.length === 0) {
    return ""
  }

  return `${iconEntries
    .map((iconEntry, index) => {
      const indentation = index === 0 ? "" : "  "
      return `${indentation}${JSON.stringify(iconEntry.iconName)}: ${JSON.stringify(iconEntry.symbolId)},`
    })
    .join("\n")}`
}

function isIconPath(filePath: string) {
  return (
    !path.relative(iconRoot, filePath).startsWith("..") &&
    extname(filePath).toLowerCase() === ".svg"
  )
}

function toPosixPath(path: string) {
  return path.replaceAll("\\", "/")
}

function injectGeneratedBanner(source: string) {
  return `${generatedBanner}${source}`
}
