import { css } from "@goddard-ai/styled-system/css"

export default {
  backdrop: css({
    position: "fixed",
    inset: "0",
    zIndex: "60",
    backgroundColor: "overlay",
    backdropFilter: "blur(4px)",
  }),
  positioner: css({
    position: "fixed",
    inset: "0",
    zIndex: "61",
    display: "grid",
    placeItems: "center",
    padding: "16px",
  }),
  content: css({
    width: "min(520px, calc(100vw - 32px))",
    display: "grid",
    gap: "14px",
    padding: "18px",
    borderRadius: "16px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "panel",
    outline: "none",
  }),
  title: css({
    display: "grid",
    gap: "4px",
    paddingRight: "40px",
  }),
  titleLabel: css({
    color: "muted",
    fontSize: "0.76rem",
    fontWeight: "720",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  }),
  titleText: css({
    color: "text",
    fontSize: "1.1rem",
    fontWeight: "760",
    lineHeight: "1.3",
  }),
  closeButton: css({
    position: "absolute",
    top: "12px",
    right: "12px",
    display: "grid",
    placeItems: "center",
    width: "32px",
    height: "32px",
    borderRadius: "10px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    color: "muted",
    cursor: "pointer",
  }),
  metaList: css({
    display: "grid",
    gap: "8px",
    margin: "0",
    padding: "0",
  }),
  metaRow: css({
    display: "grid",
    gap: "2px",
  }),
  metaTerm: css({
    color: "muted",
    fontSize: "0.76rem",
    fontWeight: "720",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  }),
  metaDetail: css({
    margin: "0",
    color: "text",
    fontSize: "0.9rem",
    lineHeight: "1.5",
  }),
  captureSection: css({
    display: "grid",
    gap: "10px",
    padding: "14px",
    borderRadius: "14px",
    border: "1px solid",
    borderColor: "border",
  }),
  captureHeading: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  }),
  captureLabel: css({
    color: "text",
    fontSize: "0.88rem",
    fontWeight: "680",
  }),
  captureStatus: css({
    color: "accentStrong",
    fontSize: "0.8rem",
    fontWeight: "700",
  }),
  captureValue: css({
    minHeight: "52px",
    display: "grid",
    placeItems: "center",
    padding: "12px",
    borderRadius: "12px",
    backgroundColor: "surface",
    color: "text",
    fontFamily: '"IBM Plex Mono", "SFMono-Regular", "Menlo", monospace',
    fontSize: "0.95rem",
    textAlign: "center",
  }),
  capturePlaceholder: css({
    color: "muted",
    fontFamily: "inherit",
    fontSize: "0.86rem",
  }),
  actionRow: css({
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
  }),
  actionButton: css({
    height: "36px",
    paddingInline: "14px",
    borderRadius: "12px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "surface",
    color: "text",
    fontSize: "0.86rem",
    fontWeight: "680",
    cursor: "pointer",
    _disabled: {
      color: "muted",
      cursor: "not-allowed",
    },
  }),
  actionButtonDanger: css({
    borderColor: "danger",
    color: "danger",
  }),
  actionButtonPrimary: css({
    borderColor: "accent",
    backgroundColor: "accent",
    color: "accentFg",
  }),
}
