import { css } from "@goddard-ai/styled-system/css"

export default {
  page: css({
    display: "grid",
    gap: "12px",
    minHeight: "100%",
    padding: "20px",
  }),
  searchField: css({
    position: "relative",
    display: "block",
  }),
  srOnly: css({
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: "0",
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: "0",
  }),
  searchIcon: css({
    position: "absolute",
    top: "50%",
    left: "14px",
    transform: "translateY(-50%)",
    color: "muted",
    pointerEvents: "none",
  }),
  searchInput: css({
    width: "100%",
    height: "42px",
    paddingLeft: "42px",
    paddingRight: "52px",
    borderRadius: "14px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "panel",
    color: "text",
    fontSize: "0.92rem",
    outline: "none",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
  }),
  recordButton: css({
    position: "absolute",
    top: "6px",
    right: "6px",
    display: "grid",
    placeItems: "center",
    width: "30px",
    height: "30px",
    borderRadius: "10px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "surface",
    color: "muted",
    cursor: "pointer",
  }),
  recordButtonActive: css({
    borderColor: "accent",
    color: "accentStrong",
  }),
  warning: css({
    padding: "10px 12px",
    borderRadius: "14px",
    border: "1px solid",
    borderColor: "accent",
    backgroundColor: "surface",
    color: "text",
    fontSize: "0.84rem",
    lineHeight: "1.5",
  }),
  error: css({
    padding: "10px 12px",
    borderRadius: "14px",
    border: "1px solid",
    borderColor: "danger",
    backgroundColor: "surface",
    color: "danger",
    fontSize: "0.84rem",
    lineHeight: "1.5",
  }),
  tableFrame: css({
    overflow: "auto",
    borderRadius: "18px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "panel",
  }),
  table: css({
    width: "100%",
    borderCollapse: "collapse",
    tableLayout: "fixed",
  }),
  headerCell: css({
    position: "sticky",
    top: "0",
    zIndex: "1",
    padding: "10px 14px",
    borderBottom: "1px solid",
    borderBottomColor: "border",
    backgroundColor: "panel",
    color: "muted",
    fontSize: "0.74rem",
    fontWeight: "720",
    letterSpacing: "0.08em",
    textAlign: "left",
    textTransform: "uppercase",
  }),
  row: css({
    _hover: {
      backgroundColor: "surface",
    },
  }),
  cell: css({
    padding: "10px 14px",
    borderBottom: "1px solid",
    borderBottomColor: "border",
    color: "text",
    fontSize: "0.88rem",
    verticalAlign: "middle",
  }),
  commandCell: css({
    fontWeight: "620",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  cellButton: css({
    width: "100%",
    padding: "0",
    border: "0",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    fontSize: "inherit",
    textAlign: "left",
  }),
  cellButtonMuted: css({
    color: "muted",
  }),
  shortcutButton: css({
    fontFamily: '"IBM Plex Mono", "SFMono-Regular", "Menlo", monospace',
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  }),
  whenButton: css({
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  }),
  whenInput: css({
    width: "100%",
    height: "32px",
    paddingInline: "10px",
    borderRadius: "10px",
    border: "1px solid",
    borderColor: "accent",
    backgroundColor: "background",
    color: "text",
    fontSize: "0.84rem",
    outline: "none",
  }),
  menuContent: css({
    display: "grid",
    gap: "4px",
    width: "220px",
    maxWidth: "var(--available-width)",
    maxHeight: "var(--available-height)",
    padding: "8px",
    overflowY: "auto",
    borderRadius: "14px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    outline: "none",
  }),
  menuItem: css({
    width: "100%",
    minHeight: "34px",
    paddingInline: "10px",
    borderRadius: "10px",
    border: "0",
    background: "transparent",
    color: "text",
    cursor: "pointer",
    fontSize: "0.84rem",
    fontWeight: "620",
    textAlign: "left",
    _hover: {
      backgroundColor: "surface",
    },
    "&[data-highlighted]": {
      backgroundColor: "surface",
    },
    _disabled: {
      color: "muted",
      cursor: "not-allowed",
    },
  }),
  menuItemDanger: css({
    color: "danger",
  }),
  empty: css({
    display: "grid",
    placeItems: "center",
    minHeight: "160px",
    color: "muted",
    fontSize: "0.88rem",
    textAlign: "center",
  }),
}
