import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, extname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"

const projectRoot = fileURLToPath(new URL("../../..", import.meta.url))
const publicDir = join(projectRoot, "public")
const outputPath = join(projectRoot, "src/support/svg-icon.tsx")
const templatePath = fileURLToPath(new URL("./svg-icon.template.tsx", import.meta.url))
const svgGlob = new Bun.Glob("**/*.svg")
const generatedBanner =
  "// Generated by the Bun svg icon build plugin. Edit the template instead.\n\n"

export function svgIconBuildPlugin() {
  return {
    name: "svg-icon-build-plugin",
    setup(build: Bun.PluginBuilder) {
      build.onStart(async () => {
        await generateSvgIconComponent()
      })
    },
  }
}

export async function generateSvgIconComponent() {
  await mkdir(publicDir, { recursive: true })

  const template = await readFile(templatePath, "utf8")
  const iconEntries = [...svgGlob.scanSync({ cwd: publicDir, absolute: true })]
    .sort((left, right) => left.localeCompare(right))
    .map((iconPath, index) => {
      const relativeIconPath = relative(publicDir, iconPath)
      const iconName = toPosixPath(relativeIconPath.slice(0, -extname(relativeIconPath).length))
      const importPath = toImportPath(relative(dirname(outputPath), iconPath))

      return {
        iconName,
        importName: `svgSource${index}`,
        importPath,
      }
    })

  const generatedSource = template
    .replace("/* SVG_ICON_IMPORTS */", buildImportBlock(iconEntries))
    .replace("/* SVG_ICON_ENTRIES */", buildIconEntryBlock(iconEntries))
  const generated = injectGeneratedBanner(generatedSource)

  await mkdir(dirname(outputPath), { recursive: true })

  let existing = ""

  try {
    existing = await readFile(outputPath, "utf8")
  } catch {
    existing = ""
  }

  if (existing === generated) {
    return
  }

  await writeFile(outputPath, generated)
}

function buildImportBlock(iconEntries: Array<{ importName: string; importPath: string }>) {
  if (iconEntries.length === 0) {
    return ""
  }

  return `${iconEntries
    .map((iconEntry) => {
      return `import ${iconEntry.importName} from "${iconEntry.importPath}?raw"`
    })
    .join("\n")}\n`
}

function buildIconEntryBlock(iconEntries: Array<{ iconName: string; importName: string }>) {
  if (iconEntries.length === 0) {
    return ""
  }

  return `${iconEntries
    .map((iconEntry) => {
      return `  ${JSON.stringify(iconEntry.iconName)}: ${iconEntry.importName},`
    })
    .join("\n")}\n`
}

function toImportPath(path: string) {
  const normalizedPath = toPosixPath(path)

  if (normalizedPath.startsWith(".")) {
    return normalizedPath
  }

  return `./${normalizedPath}`
}

function toPosixPath(path: string) {
  return path.replaceAll("\\", "/")
}

function injectGeneratedBanner(source: string) {
  const firstLineBreakIndex = source.indexOf("\n")

  if (firstLineBreakIndex === -1) {
    return `${generatedBanner}${source}`
  }

  return `${source.slice(0, firstLineBreakIndex + 1)}${generatedBanner}${source.slice(firstLineBreakIndex + 1)}`
}
