import { css } from "@goddard-ai/styled-system/css"
import { token } from "@goddard-ai/styled-system/tokens"

export default {
  field: css({
    minWidth: "0",
  }),
  tooltipTrigger: css({
    display: "block",
    minWidth: "0",
  }),
  trigger: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "6px",
    width: "100%",
    minHeight: "28px",
    padding: "0",
    border: "none",
    backgroundColor: "transparent",
    color: "text",
    cursor: "pointer",
    textAlign: "left",
    outline: "none",
    transition: "color 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    _hover: {
      color: "accentStrong",
    },
    _focusVisible: {
      borderRadius: "8px",
      boxShadow: `0 0 0 3px color-mix(in srgb, ${token.var("colors.accent")} 18%, transparent)`,
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.5",
    },
  }),
  triggerLabel: css({
    minWidth: "0",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "0.88rem",
    fontWeight: "600",
  }),
  triggerPlaceholder: css({
    color: "muted",
    fontWeight: "500",
  }),
  chevron: css({
    flexShrink: "0",
    transition: "transform 160ms cubic-bezier(0.23, 1, 0.32, 1)",
  }),
  tooltipContent: css({
    display: "grid",
    gap: "4px",
    alignItems: "start",
  }),
  tooltipShortcut: css({
    color: "muted",
    fontSize: "0.72rem",
    fontWeight: "560",
    lineHeight: "1.2",
  }),
  menu: css({
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    width: "var(--reference-width)",
    minWidth: "min(280px, var(--available-width))",
    maxWidth: "min(calc(100vw - 32px), var(--available-width))",
    maxHeight: "min(360px, var(--available-height))",
    overflow: "hidden",
    border: "none",
    borderRadius: "14px",
    backgroundColor: "panel",
    boxShadow: "0 12px 28px rgba(98, 112, 128, 0.16)",
    outline: "none",
  }),
  menuFilter: css({
    width: "100%",
    padding: "10px 0 8px",
    border: "none",
    borderBottom: "1px solid",
    borderBottomColor: "border",
    backgroundColor: "transparent",
    color: "text",
    fontSize: "0.84rem",
    outline: "none",
    _placeholder: {
      color: "muted",
    },
    _focusVisible: {
      borderBottomColor: "accentStrong",
    },
  }),
  menuList: css({
    display: "grid",
    gap: "0",
    minHeight: "0",
    margin: "0",
    padding: "0",
    overflowY: "auto",
    listStyle: "none",
  }),
  menuButton: css({
    display: "block",
    width: "100%",
    minHeight: "32px",
    padding: "0",
    border: "none",
    backgroundColor: "transparent",
    color: "text",
    cursor: "pointer",
    fontSize: "0.86rem",
    fontWeight: "560",
    lineHeight: "32px",
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    transition: "background-color 120ms ease",
    _hover: {
      backgroundColor: `color-mix(in srgb, ${token.var("colors.accent")} 16%, transparent)`,
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.5",
    },
  }),
  menuButtonActive: css({
    backgroundColor: `color-mix(in srgb, ${token.var("colors.accent")} 18%, transparent)`,
  }),
  menuEmpty: css({
    display: "grid",
    placeItems: "center",
    minHeight: "64px",
    color: "muted",
    fontSize: "0.82rem",
    textAlign: "center",
  }),
}
