/**
 * This file is auto-generated. Do not edit manually.
 */

export const ACPAdapterNames = [
  "agoragentic-acp",
  "amp-acp",
  "auggie",
  "autohand",
  "claude-acp",
  "cline",
  "codebuddy-code",
  "codex-acp",
  "cortex-code",
  "corust-agent",
  "crow-cli",
  "cursor",
  "deepagents",
  "devin",
  "dimcode",
  "dirac",
  "factory-droid",
  "fast-agent",
  "gemini",
  "github-copilot-cli",
  "glm-acp-agent",
  "goose",
  "grok-build",
  "junie",
  "kilo",
  "kimi",
  "minion-code",
  "mistral-vibe",
  "nova",
  "opencode",
  "pi-acp",
  "poolside",
  "qoder",
  "qwen-code",
  "sigit",
  "stakpak",
  "vtcode",
] as const

export type ACPAdapterName = (typeof ACPAdapterNames)[number] | (string & {})
