// Generated by the Vite svg icon build plugin. Edit the template instead.

export const svgIconSymbolIds = {
  "close-tab": "close-tab",
  "logo": "logo",
  "new-session": "new-session",
  "settings": "settings",
  "tabs/changes": "tabs-changes",
  "tabs/extensions": "tabs-extensions",
  "tabs/home": "tabs-home",
  "tabs/inbox": "tabs-inbox",
  "tabs/pages": "tabs-pages",
  "tabs/projects": "tabs-projects",
  "tabs/pull-request": "tabs-pull-request",
  "tabs/roadmap": "tabs-roadmap",
  "tabs/search": "tabs-search",
  "tabs/sessions": "tabs-sessions",
  "tabs/skills": "tabs-skills",
  "tabs/spec": "tabs-spec",
  "tabs/tasks": "tabs-tasks",
  "what-next": "what-next",
} as const
