import { css } from "@goddard-ai/styled-system/css"
import { token } from "@goddard-ai/styled-system/tokens"

const accentColor = token.var("colors.accent")
const accentStrongColor = token.var("colors.accentStrong")
const backgroundColor = token.var("colors.background")
const borderColor = token.var("colors.border")
const panelColor = token.var("colors.panel")
const textColor = token.var("colors.text")

export default {
  actionButton: css({
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    backgroundColor: "transparent",
    color: "accentStrong",
    cursor: "pointer",
    transition:
      "background-color 200ms cubic-bezier(0.23, 1, 0.32, 1), color 200ms cubic-bezier(0.23, 1, 0.32, 1), opacity 200ms cubic-bezier(0.23, 1, 0.32, 1)",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
  }),
  root: css({
    display: "grid",
    gridTemplateColumns: "42px minmax(0, 1fr)",
    gridTemplateRows: "48px minmax(0, 1fr)",
    width: "100%",
    height: "100vh",
    maxHeight: "100vh",
    overflow: "hidden",
    backgroundColor: "background",
    color: "text",
    fontFamily: '"Inter Tight", sans-serif',
  }),
  header: css({
    gridColumn: "1 / -1",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    height: "48px",
    paddingRight: "11px",
    backgroundColor: "surface",
    boxShadow: `0 0.5px 0 ${borderColor}`,
    zIndex: "2",
  }),
  switcher: css({
    position: "absolute",
    left: "50%",
    top: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "min(40%, 320px)",
    minWidth: "140px",
    transform: "translateX(-50%)",
  }),
  actions: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "12px",
    height: "28px",
  }),
  actionGroup: css({
    display: "flex",
    alignItems: "center",
    padding: "3px",
    borderRadius: "14px",
    backgroundColor: `color-mix(in srgb, ${accentColor} 18%, transparent)`,
    _hover: {
      "& > span": {
        opacity: "0",
      },
    },
  }),
  actionDivider: css({
    width: "1px",
    height: "10px",
    backgroundColor: accentStrongColor,
    opacity: "0.3",
    transition: "opacity 200ms cubic-bezier(0.23, 1, 0.32, 1)",
  }),
  settingsButton: css({
    width: "32px",
    height: "28px",
    borderRadius: "9px",
    color: "muted",
    _hover: {
      backgroundColor: "panel",
      color: "text",
    },
  }),
  nav: css({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    width: "42px",
    height: "100%",
    overflowY: "auto",
    overflowX: "hidden",
    background: `linear-gradient(180deg, ${panelColor} 12.32%, ${backgroundColor} 100%)`,
  }),
  navDivider: css({
    width: "70%",
    minHeight: "0.5px",
    marginTop: "6px",
    marginBottom: "6px",
    backgroundColor: "border",
  }),
  main: css({
    display: "grid",
    gridTemplateRows: "31px minmax(0, 1fr)",
    minWidth: "0",
    minHeight: "0",
  }),
  tabStrip: css({
    position: "relative",
    display: "flex",
    alignItems: "stretch",
    minHeight: "31px",
    height: "31px",
    overflowX: "auto",
    overflowY: "hidden",
    backgroundColor: "surface",
    boxShadow: `inset 0 -0.5px 0 ${borderColor}`,
  }),
  tabList: css({
    position: "relative",
    display: "flex",
    alignItems: "stretch",
    minWidth: "max-content",
    height: "31px",
  }),
  indicator: css({
    position: "absolute",
    bottom: "0",
    height: "0.5px",
    backgroundColor: "accentStrong",
    transition:
      "transform 180ms cubic-bezier(0.23, 1, 0.32, 1), width 180ms cubic-bezier(0.23, 1, 0.32, 1), opacity 180ms cubic-bezier(0.23, 1, 0.32, 1)",
  }),
  actionItem: css({
    width: "46px",
    height: "22px",
    borderRadius: "11px",
    _hover: {
      backgroundColor: `color-mix(in srgb, ${accentColor} 24%, ${panelColor})`,
    },
  }),
  sidebarItem: css({
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "42px",
    minWidth: "42px",
    height: "42px",
    minHeight: "42px",
    border: "none",
    backgroundColor: "transparent",
    color: `color-mix(in srgb, ${textColor} 38%, transparent)`,
    cursor: "pointer",
    transition: "color 180ms cubic-bezier(0.23, 1, 0.32, 1)",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "-2px",
    },
    _hover: {
      color: "text",
    },
  }),
  tab: css({
    position: "relative",
    display: "inline-flex",
    alignItems: "stretch",
    height: "30px",
    flexShrink: "0",
  }),
  tabButton: css({
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    height: "30px",
    flexShrink: "0",
    border: "none",
    borderRadius: "0",
    backgroundColor: "surface",
    cursor: "pointer",
    transition:
      "color 180ms cubic-bezier(0.23, 1, 0.32, 1), opacity 180ms cubic-bezier(0.23, 1, 0.32, 1)",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "-2px",
    },
  }),
  tabIcon: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    marginRight: "5px",
    marginTop: "5px",
    marginBottom: "5px",
    transition: "color 180ms cubic-bezier(0.23, 1, 0.32, 1)",
  }),
  tabLabel: css({
    fontSize: "12px",
    fontWeight: "400",
    letterSpacing: "0.02em",
    lineHeight: "1.21",
    whiteSpace: "nowrap",
    transition: "color 180ms cubic-bezier(0.23, 1, 0.32, 1)",
  }),
  tabTail: css({
    display: "grid",
    placeItems: "center",
    width: "32px",
    height: "30px",
    marginRight: "0",
    flexShrink: "0",
    cursor: "pointer",
  }),
  tabDirty: css({
    gridArea: "1 / 1",
    width: "6px",
    height: "6px",
    borderRadius: "999px",
    backgroundColor: "accentStrong",
    transition: "opacity 180ms cubic-bezier(0.23, 1, 0.32, 1)",
  }),
  tabClose: css({
    gridArea: "1 / 1",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "18px",
    height: "18px",
    padding: "0",
    border: "none",
    borderRadius: "999px",
    backgroundColor: "transparent",
    color: `color-mix(in srgb, ${textColor} 42%, transparent)`,
    cursor: "pointer",
    opacity: "0",
    transition:
      "opacity 180ms cubic-bezier(0.23, 1, 0.32, 1), background-color 180ms cubic-bezier(0.23, 1, 0.32, 1), color 180ms cubic-bezier(0.23, 1, 0.32, 1)",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "1px",
      opacity: "1",
      backgroundColor: `color-mix(in srgb, ${textColor} 10%, transparent)`,
    },
    _hover: {
      backgroundColor: `color-mix(in srgb, ${textColor} 10%, transparent)`,
      color: "text",
    },
  }),
  icon: css({
    display: "inline-block",
    flexShrink: "0",
  }),
}
