import { css } from "@goddard-ai/styled-system/css"

export default {
  row: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "12px",
    alignItems: "center",
    paddingInline: "16px",
    paddingBlock: "10px",
    borderBottom: "1px solid",
    borderColor: "border",
    "@media (hover: hover) and (pointer: fine)": {
      _hover: {
        backgroundColor: "surface",
      },
      '&:hover [data-actions="true"]': {
        opacity: 1,
        pointerEvents: "auto",
      },
    },
    '&:focus-within [data-actions="true"]': {
      opacity: 1,
      pointerEvents: "auto",
    },
  }),
  mainButton: css({
    display: "grid",
    gap: "4px",
    minWidth: "0",
    padding: "0",
    border: "none",
    background: "transparent",
    color: "inherit",
    textAlign: "left",
    cursor: "pointer",
    borderRadius: "8px",
    outline: "none",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
  }),
  metaRow: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    minWidth: "0",
  }),
  repoGroup: css({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: "0",
  }),
  statusIcon: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: "0",
  }),
  srOnly: css({
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: "0",
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: "0",
  }),
  repository: css({
    color: "muted",
    fontFamily: '"SF Mono", "JetBrains Mono", "Menlo", monospace',
    fontSize: "0.76rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  updated: css({
    color: "muted",
    fontSize: "0.76rem",
    flexShrink: "0",
  }),
  title: css({
    minWidth: "0",
    color: "text",
    fontSize: "0.93rem",
    fontWeight: "600",
    lineHeight: "1.45",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  actions: css({
    display: "flex",
    alignItems: "center",
    gap: "6px",
    "@media (hover: hover) and (pointer: fine)": {
      opacity: 0,
      pointerEvents: "none",
      transition: "opacity 120ms cubic-bezier(0.23, 1, 0.32, 1)",
    },
  }),
  actionButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    height: "30px",
    paddingInline: "10px",
    borderRadius: "9px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    color: "text",
    fontSize: "0.78rem",
    fontWeight: "600",
    cursor: "pointer",
    transition:
      "background-color 160ms cubic-bezier(0.23, 1, 0.32, 1), border-color 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
    "@media (hover: hover) and (pointer: fine)": {
      _hover: {
        borderColor: "accent",
        backgroundColor: "surface",
      },
    },
  }),
}
