import { css } from "@goddard-ai/styled-system/css"

export default {
  panel: css({
    display: "flex",
    flexDirection: "column",
    minHeight: "0",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "16px",
    backgroundColor: "panel",
    overflow: "hidden",
  }),
  title: css({
    color: "text",
    fontSize: "1.25rem",
    fontWeight: "700",
    lineHeight: "1.25",
  }),
  body: css({
    color: "muted",
    fontSize: "0.9rem",
    lineHeight: "1.6",
  }),
  quietLabel: css({
    color: "muted",
    fontSize: "0.78rem",
    fontWeight: "600",
  }),
  label: css({
    color: "text",
    fontSize: "0.84rem",
    fontWeight: "600",
  }),
  buttonBase: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    minWidth: "0",
    height: "36px",
    paddingInline: "12px",
    borderRadius: "10px",
    border: "1px solid",
    fontSize: "0.86rem",
    fontWeight: "600",
    cursor: "pointer",
    transition:
      "background-color 160ms cubic-bezier(0.23, 1, 0.32, 1), border-color 160ms cubic-bezier(0.23, 1, 0.32, 1), color 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.48",
    },
  }),
  secondaryButton: css({
    borderColor: "border",
    backgroundColor: "background",
    color: "text",
    "@media (hover: hover) and (pointer: fine)": {
      _hover: {
        borderColor: "accent",
        backgroundColor: "surface",
      },
    },
  }),
  primaryButton: css({
    borderColor: "accent",
    backgroundColor: "surface",
    color: "text",
    "@media (hover: hover) and (pointer: fine)": {
      _hover: {
        borderColor: "accentStrong",
        backgroundColor: "background",
      },
    },
  }),
  dangerButton: css({
    borderColor: "border",
    backgroundColor: "background",
    color: "muted",
    "@media (hover: hover) and (pointer: fine)": {
      _hover: {
        borderColor: "danger",
        color: "danger",
        backgroundColor: "surface",
      },
    },
  }),
  dialogOverlay: css({
    position: "fixed",
    inset: "0",
    backgroundColor: "overlay",
    backdropFilter: "blur(6px)",
    opacity: "1",
    transition: "opacity 180ms cubic-bezier(0.23, 1, 0.32, 1)",
    "@starting-style": {
      opacity: "0",
    },
  }),
  dialogContent: css({
    width: "min(560px, calc(100vw - 32px))",
    maxHeight: "calc(100vh - 32px)",
    overflowY: "auto",
    padding: "20px",
    borderRadius: "16px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "panel",
    opacity: "1",
    transform: "translateY(0)",
    transition:
      "opacity 180ms cubic-bezier(0.23, 1, 0.32, 1), transform 180ms cubic-bezier(0.23, 1, 0.32, 1)",
    outline: "none",
    "@starting-style": {
      opacity: "0",
      transform: "translateY(8px)",
    },
  }),
  dialogPositioner: css({
    position: "fixed",
    inset: "0",
    display: "grid",
    placeItems: "center",
    padding: "16px",
  }),
  textInput: css({
    width: "100%",
    height: "40px",
    paddingInline: "12px",
    borderRadius: "10px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    color: "text",
    fontSize: "0.9rem",
    outline: "none",
    transition:
      "border-color 160ms cubic-bezier(0.23, 1, 0.32, 1), background-color 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    _focusVisible: {
      borderColor: "accentStrong",
    },
    _disabled: {
      opacity: "0.7",
    },
  }),
  root: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 2fr) minmax(320px, 1fr)",
    gap: "20px",
    height: "100%",
    padding: "24px",
    "@media (max-width: 1040px)": {
      gridTemplateColumns: "1fr",
    },
  }),
  sectionHeader: css({
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "16px",
    padding: "20px",
    borderBottom: "1px solid",
    borderColor: "border",
  }),
  sectionCopy: css({
    display: "grid",
    gap: "6px",
    minWidth: "0",
  }),
  empty: css({
    display: "grid",
    alignContent: "start",
    gap: "12px",
    minHeight: "220px",
    padding: "20px",
  }),
  emptyCopy: css({
    display: "grid",
    gap: "8px",
    maxWidth: "30rem",
  }),
  asideBody: css({
    display: "grid",
    gap: "16px",
    padding: "20px",
  }),
  intro: css({
    display: "grid",
    gap: "6px",
  }),
  subheading: css({
    color: "text",
    fontSize: "1rem",
    fontWeight: "700",
  }),
  selectedTitle: css({
    color: "text",
    fontSize: "1.05rem",
    fontWeight: "700",
  }),
  cardList: css({
    display: "grid",
    gap: "12px",
  }),
  list: css({
    listStyle: "none",
    margin: "0",
    padding: "0",
    minHeight: "0",
    overflowY: "auto",
    "& > li + li": {
      borderTop: "1px solid",
      borderColor: "border",
    },
  }),
  row: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "12px",
    padding: "14px 16px",
    borderInlineStart: "2px solid",
  }),
  rowButton: css({
    display: "grid",
    gap: "4px",
    minWidth: "0",
    padding: "0",
    border: "none",
    background: "transparent",
    color: "inherit",
    textAlign: "left",
    cursor: "pointer",
  }),
  rowHeader: css({
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "8px",
  }),
  rowTitle: css({
    color: "text",
    fontSize: "0.96rem",
    fontWeight: "600",
    lineHeight: "1.4",
  }),
  selectedBadge: css({
    color: "accentStrong",
    fontSize: "0.78rem",
    fontWeight: "600",
  }),
  path: css({
    color: "muted",
    fontFamily: '"SF Mono", "JetBrains Mono", "Menlo", monospace',
    fontSize: "0.8rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  rowActions: css({
    display: "flex",
    alignItems: "center",
    gap: "8px",
  }),
  infoCard: css({
    display: "grid",
    gap: "4px",
    padding: "12px",
    borderRadius: "12px",
    border: "1px solid",
    borderColor: "border",
  }),
  infoValue: css({
    margin: "0",
    color: "text",
    fontWeight: "600",
    lineHeight: "1.6",
    wordBreak: "break-word",
  }),
  form: css({
    display: "grid",
    gap: "16px",
  }),
  dialogHeader: css({
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "16px",
  }),
  dialogHeaderCopy: css({
    display: "grid",
    gap: "6px",
  }),
  closeButton: css({
    display: "grid",
    placeItems: "center",
    width: "32px",
    height: "32px",
    borderRadius: "10px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    color: "muted",
    cursor: "pointer",
  }),
  field: css({
    display: "grid",
    gap: "6px",
  }),
  browseRow: css({
    display: "flex",
    justifyContent: "flex-start",
  }),
  dialogActions: css({
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
  }),
}
