import { css } from "@goddard-ai/styled-system/css"

export default {
  trigger: css({
    display: "inline-flex",
    alignItems: "center",
    width: "100%",
    height: "28px",
    paddingInline: "12px",
    border: "none",
    borderRadius: "6px",
    backgroundColor: "panel",
    color: "muted",
    cursor: "pointer",
    textAlign: "left",
    transition:
      "background-color 180ms cubic-bezier(0.23, 1, 0.32, 1), color 180ms cubic-bezier(0.23, 1, 0.32, 1)",
    _hover: {
      backgroundColor: "surface",
      color: "text",
    },
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
  }),
  triggerLabel: css({
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "13px",
    fontWeight: "400",
    letterSpacing: "0.02em",
    lineHeight: "1.21",
  }),
  content: css({
    display: "grid",
    gap: "8px",
    width: "var(--reference-width)",
    minWidth: "320px",
    marginTop: "10px",
    padding: "10px",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "14px",
    backgroundColor: "background",
    outline: "none",
  }),
  searchField: css({
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minHeight: "38px",
    paddingInline: "12px",
    borderRadius: "10px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "surface",
    color: "muted",
    transition:
      "border-color 160ms cubic-bezier(0.23, 1, 0.32, 1), background-color 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    _focusWithin: {
      borderColor: "accent",
      backgroundColor: "surface",
    },
  }),
  srOnly: css({
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: "0",
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: "0",
  }),
  searchInput: css({
    width: "100%",
    height: "28px",
    border: "none",
    outline: "none",
    backgroundColor: "transparent",
    color: "text",
    fontSize: "0.9rem",
    fontWeight: "600",
    "&::placeholder": {
      color: "muted",
    },
  }),
  list: css({
    display: "grid",
    gap: "2px",
    maxHeight: "280px",
    overflowY: "auto",
    listStyle: "none",
    padding: "0",
    margin: "0",
  }),
  item: css({
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "12px",
    width: "100%",
    minHeight: "44px",
    padding: "8px 10px",
    border: "none",
    borderRadius: "10px",
    backgroundColor: "transparent",
    color: "text",
    cursor: "pointer",
    textAlign: "left",
    transition: "background-color 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
    "&[data-highlighted='true']": {
      backgroundColor: "surface",
    },
  }),
  itemBody: css({
    display: "grid",
    gap: "2px",
    minWidth: "0",
  }),
  itemTitle: css({
    fontSize: "0.88rem",
    fontWeight: "650",
  }),
  itemTitleEllipsis: css({
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "0.88rem",
    fontWeight: "650",
  }),
  itemDetail: css({
    color: "muted",
    fontSize: "0.76rem",
    lineHeight: "1.4",
  }),
  itemDetailEllipsis: css({
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "muted",
    fontSize: "0.76rem",
    lineHeight: "1.4",
  }),
  activeBadge: css({
    color: "accentStrong",
    fontSize: "0.72rem",
    fontWeight: "600",
    whiteSpace: "nowrap",
  }),
  empty: css({
    margin: "0",
    padding: "10px",
    color: "muted",
    fontSize: "0.84rem",
  }),
}
